<a href="https://colab.research.google.com/github/andreserenaquintilla/Ejercicios_Big_Data/blob/main/Guia_Python_BDIA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Guía práctica de Python para BDIA

**2.º CFGS Desarrollo de Aplicaciones Web (DAW)**  
**Módulo: Big Data e Inteligencia Artificial**

Este cuaderno está diseñado para alumnado que nunca ha trabajado con Python. El objetivo es construir progresivamente la base necesaria para el resto del curso: programación básica, estructuras de datos, funciones, lectura de datos, NumPy, Pandas, APIs y preparación de datos para Machine Learning.

El cuaderno está pensado para ejecutarse en **Google Colab** o en Jupyter Notebook/JupyterLab.

La metodología será siempre:

**explicación → ejemplo → prueba → ejercicio → aplicación a datos**.

## Índice

1. Primer contacto con Python
2. Variables y tipos
3. Operadores
4. Cadenas de texto
5. Listas, tuplas, conjuntos y diccionarios
6. Condicionales
7. Bucles
8. Funciones
9. Comprensiones y herramientas útiles
10. Errores y excepciones
11. Módulos y librerías
12. Archivos, CSV y JSON
13. NumPy
14. Pandas
15. Limpieza y transformación
16. Agrupaciones y combinación de datos
17. APIs REST
18. Preparación para Machine Learning
19. Mini proyecto final

# 1. Primer contacto con Python

Python será nuestro lenguaje principal para trabajar con datos y herramientas de Inteligencia Artificial.

En un notebook podemos combinar celdas de **Markdown**, donde escribimos explicaciones, y celdas de **código**, donde ejecutamos Python. Esto permite aprender de forma interactiva.

En Google Colab no necesitamos preparar inicialmente un entorno Python local.

In [1]:
print("Hola, Python")
print("Bienvenidos a BDIA")

Hola, Python
Bienvenidos a BDIA

### Ejercicio 1

Modifica la celda anterior para mostrar:

- tu nombre;
- tu ciclo formativo;
- el módulo;
- una frase sobre qué esperas aprender.

In [1]:
print("Hola, mi nombre es Andrés Serena Quintilla")
print("Actualmente, estoy matriculado en el curso de segundo de DAW")
print("El módulo donde estoy realizando esta prueba es el de Big Data e IA")
print("Espero aprobar, eso de primeras, pero sobretodo, espero apdrender todo lo que pueda este ciclo y esta asignatura ofrecerme")

Hola, mi nombre es Andrés Serena Quintilla
Actualmente, estoy matriculado en el curso de segundo de DAW
El módulo donde estoy realizando esta prueba es el de Big Data e IA
Espero aprobar, eso de primeras, pero sobretodo, espero apdrender todo lo que pueda este ciclo y esta asignatura ofrecerme

## Comentarios

Los comentarios sirven para documentar el código y comienzan con `#`.

In [2]:
# Esto es un comentario
print("Esto sí se ejecuta")

Esto sí se ejecuta

# 2. Variables y tipos de datos

Una variable permite asociar un nombre a un valor.

Los tipos básicos que utilizaremos con frecuencia son:

- `str`: texto
- `int`: entero
- `float`: decimal
- `bool`: verdadero/falso

In [3]:
nombre = "Ana"
edad = 20
altura = 1.72
es_estudiante = True

print(nombre)
print(edad)
print(altura)
print(es_estudiante)

print(type(nombre))
print(type(edad))
print(type(altura))
print(type(es_estudiante))

Ana
20
1.72
True
<class 'str'>
<class 'int'>
<class 'float'>
<class 'bool'>

### Ejercicio 2

Crea variables para representar un producto:

- nombre;
- precio;
- unidades;
- disponible.

Muestra sus valores y sus tipos.

In [4]:
# Escribe aquí tu solución
nombre = "Nintendo Switch"
precio = "499"
unidades = "800"
disponible = "true"

print(nombre)
print(precio)
print(unidades)
print(disponible)

print(type(nombre))
print(type(precio))
print(type(unidades))
print(type(disponible))

Nintendo Switch
499
800
true
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>

# 3. Operadores

Los operadores aritméticos más habituales son `+`, `-`, `*`, `/`, `//`, `%` y `**`.

Las comparaciones producen valores booleanos.

In [5]:
a = 10
b = 3

print("suma:", a + b)
print("resta:", a - b)
print("multiplicación:", a * b)
print("división:", a / b)
print("división entera:", a // b)
print("resto:", a % b)
print("potencia:", a ** b)

print("a es mayor que b:", a > b)
print("a es igual a b:", a == b)

suma: 13
resta: 7
multiplicación: 30
división: 3.3333333333333335
división entera: 3
resto: 1
potencia: 1000
a es mayor que b: True
a es igual a b: False

### Ejercicio 3

Tenemos:

```python
precio = 49.90
unidades = 3
```

Calcula el importe, un descuento del 10 % y el importe final.

In [6]:
precio = 49.90
unidades = 3

# Completa el ejercicio

importeTotal = precio * unidades
print(importeTotal)

descuento10 = importeTotal * 0.1
print(descuento10)

#importeTotalDescuento = importeTotal - descuento10
#print(importeTotalDescuento)

importeTotalDescuento = importeTotal * 0.9
print(importeTotalDescuento)

149.7
14.969999999999999
134.73

# 4. Cadenas de texto

Los textos son objetos de tipo `str`. Podemos concatenarlos, medir su longitud y aplicar métodos.

In [7]:
nombre = "Ana"
curso = "DAW"

print(nombre + " - " + curso)
print(len(nombre))
print(nombre.upper())
print(nombre.lower())

Ana - DAW
3
ANA
ana

## f-strings

Las f-strings permiten construir textos incorporando variables.

In [8]:
nombre = "Ana"
nota = 8.5
print(f"{nombre} ha obtenido un {nota}")

Ana ha obtenido un 8.5

### Ejercicio 4

Crea una frase con nombre, edad y nota utilizando una f-string. Prueba también `upper()`, `lower()`, `strip()` y `replace()`.

In [9]:
# Escribe aquí tu solución

nombre = "Andrés Serena Quintilla"
edad = "26"
nota = "8"

print(f"El nombre del alumno es {nombre.replace("s", "").replace("i", "").replace("l", "p").replace(" ", "")}, tiene {edad} años y ha sacado en el examen un {nota} sobre 10.")

El nombre del alumno es AndréSerenaQuntppa, tiene 26 años y ha sacado en el examen un 8 sobre 10.

# 5. Estructuras de datos

Las estructuras fundamentales que necesitamos conocer antes de trabajar con datos son:

- **lista**: ordenada y modificable;
- **tupla**: secuencia ordenada;
- **set**: valores únicos;
- **diccionario**: pares clave-valor.

In [10]:
frutas = ["manzana", "pera", "naranja"]
coordenadas = (39.47, -0.38)
numeros = {1, 2, 3, 3}
alumno = {"nombre": "Ana", "edad": 20, "nota": 8.5}

print(frutas)
print(coordenadas)
print(numeros)
print(alumno)

['manzana', 'pera', 'naranja']
(39.47, -0.38)
{1, 2, 3}
{'nombre': 'Ana', 'edad': 20, 'nota': 8.5}

## Índices y slicing

Python comienza a contar desde cero.

In [11]:
frutas = ["manzana", "pera", "naranja", "plátano", "kiwi"]

print(frutas[0])
print(frutas[-1])
print(frutas[1:4])
print(frutas[:3])
print(frutas[2:])
print(frutas[::-1])

manzana
kiwi
['pera', 'naranja', 'plátano']
['manzana', 'pera', 'naranja']
['naranja', 'plátano', 'kiwi']
['kiwi', 'plátano', 'naranja', 'pera', 'manzana']

### Ejercicio 5

Con:

```python
notas = [7, 5, 9, 6, 8, 10, 4]
```

Obtén la primera nota, la última, las tres primeras, una parte intermedia y la lista invertida.

In [12]:
notas = [7, 5, 9, 6, 8, 10, 4]

# Escribe aquí tu solución

print(notas[0])
print(notas[6])
print(notas[0:3])
print(notas[2:5])
print(notas[::-1])

7
4
[7, 5, 9]
[9, 6, 8]
[4, 10, 8, 6, 9, 5, 7]

## Diccionarios

In [13]:
alumno = {"nombre": "Ana", "edad": 20, "nota": 8.5}

print(alumno["nombre"])
print(alumno["nota"])

alumno["nota"] = 9
alumno["curso"] = "DAW2"
print(alumno)

Ana
8.5
{'nombre': 'Ana', 'edad': 20, 'nota': 9, 'curso': 'DAW2'}

### Ejercicio 6

Crea un diccionario de un producto con nombre, categoría, precio y stock. Modifica el stock y añade un descuento.

In [14]:
# Escribe aquí tu solución

producto = {"nombre": "Switch 2", "categoria": "consola", "precio": "499", "stock": "8000"}
print(producto)

producto["stock"] = "7000"
print(producto)

producto["descuento"] = "25"
print(producto)

{'nombre': 'Switch 2', 'categoria': 'consola', 'precio': '499', 'stock': '8000'}
{'nombre': 'Switch 2', 'categoria': 'consola', 'precio': '499', 'stock': '7000'}
{'nombre': 'Switch 2', 'categoria': 'consola', 'precio': '499', 'stock': '7000', 'descuento': '25'}

# 6. Condicionales

Los condicionales permiten ejecutar diferentes instrucciones dependiendo de una condición.

In [15]:
nota = 7.5

if nota >= 9:
    resultado = "Sobresaliente"
elif nota >= 7:
    resultado = "Notable"
elif nota >= 5:
    resultado = "Aprobado"
else:
    resultado = "Suspenso"

print(resultado)

Notable

Las condiciones pueden combinarse con `and`, `or` y `not`.

In [16]:
edad = 20
tiene_carnet = True

if edad >= 18 and tiene_carnet:
    print("Puede conducir")
else:
    print("No puede conducir")

Puede conducir

### Ejercicio 7

Una tienda ofrece envío gratuito si el pedido supera 50 € **o** el cliente tiene una suscripción.

In [17]:
importe = 42
es_suscriptor = False

# Escribe aquí tu solución

if importe >= 50 or es_suscriptor:
  print("El envio es gratis")
else:
  print("Ha de pagar envio, suscribase o llegue a 50 euros para que sea gratis")

Ha de pagar envio, suscribase o llegue a 50 euros para que sea gratis

# 7. Bucles

`for` permite recorrer una colección o una secuencia.

In [18]:
frutas = ["manzana", "pera", "naranja"]

for fruta in frutas:
    print(fruta)

manzana
pera
naranja

In [19]:
#for numero in range(1, 6):
    #print(numero)

for numero in range(1, 6):
  print(numero)
for numero in range(6, 11):
  print(numero)

1
2
3
4
5
6
7
8
9
10

`while` repite instrucciones mientras una condición sea verdadera.

In [20]:
contador = 1

while contador <= 5:
    print(contador)
    contador += 1

1
2
3
4
5

### Ejercicio 8

Muestra únicamente las notas aprobadas.

In [21]:
notas = [4, 7, 8, 3, 9, 5, 6]

# Escribe aquí tu solución

for nota in notas:
  if nota >= 5:
    print(nota)

7
8
9
5
6

# 8. Funciones

Las funciones permiten organizar y reutilizar código.

In [22]:
def saludar(nombre):
    return f"Hola, {nombre}"

print(saludar("Ana"))

Hola, Ana

In [23]:
def calcular_media(numeros):
    return sum(numeros) / len(numeros)

notas = [7, 8, 9, 6]
print(calcular_media(notas))

7.5

In [24]:
def f(x):
    return 2*x
y = f(3)
print(y) # 6

6

### Ejercicio 9

Crea una función `es_par(numero)` que devuelva `True` si el número es par y `False` en caso contrario.

In [25]:
# Escribe aquí tu solución
def es_par(numero1):
  if numero1 % 2 == 0:
    return True
  else:
    return False
print(es_par(8))

True

# 9. Comprensiones y herramientas útiles

Las comprensiones permiten construir listas de forma compacta.

In [26]:
numeros = [1, 2, 3, 4, 5]

cuadrados = [numero ** 2 for numero in numeros]
print(cuadrados)

pares = [numero for numero in numeros if numero % 2 == 0]
print(pares)

[1, 4, 9, 16, 25]
[2, 4]

## `enumerate()` y `zip()`

Son herramientas muy útiles cuando trabajamos con colecciones y datos.

In [27]:
frutas = ["manzana", "pera", "naranja"]

for posicion, fruta in enumerate(frutas):
    print(posicion, fruta)

0 manzana
1 pera
2 naranja

In [29]:
nombres = ["Ana", "Luis", "Marta",]
notas = [8, 6, 9,]

for nombre, nota in zip(nombres, notas, strict=True):
    print(nombre, nota)
print(list(zip(nombres, notas)))

Ana 8
Luis 6
Marta 9
[('Ana', 8), ('Luis', 6), ('Marta', 9)]

### Ejercicio 10

Con una lista de temperaturas:

1. crea una lista con las temperaturas superiores a 20;
2. muestra posición y temperatura;
3. calcula la media.

In [30]:
temperaturas = [18, 21, 25, 19, 30, 17]

# 1. temperaturas que superan 20
superiores20 = [temperatura for temperatura in temperaturas if temperatura > 20]

# 2. todas las temperaturas con su posición y su media
print("Mostramos primero todas las temperaturas")
for posicion, temperatura in enumerate(temperaturas):
    print(posicion, temperatura)

media = sum(temperaturas) / len(temperaturas)
print(f"La media de todas las temperaturas es {round(media, 2)} grados.")

# 3. lo mismo, pero solo con las que superan 20
print("Ahora mostramos solo las temperaturas que superan los 20 grados")
for posicion, temperatura in enumerate(superiores20):
    print(posicion, temperatura)

media_superiores20 = sum(superiores20) / len(superiores20)
print(f"La media de las temperaturas superiores a 20º es {round(media_superiores20, 2)} grados")

Mostramos primero todas las temperaturas
0 18
1 21
2 25
3 19
4 30
5 17
La media de todas las temperaturas es 21.67 grados.
Ahora mostramos solo las temperaturas que superan los 20 grados
0 21
1 25
2 30
La media de las temperaturas superiores a 20º es 25.33 grados

# 10. Errores y excepciones

Los errores forman parte normal de la programación.

`try` y `except` permiten controlar determinadas excepciones.

In [31]:
try:
    numero = int(input("Introduce un número: "))
    resultado = 100 / numero
    print(resultado)
except ValueError:
    print("Debes introducir un número entero.")
except ZeroDivisionError:
    print("No se puede dividir entre cero.")

Introduce un número: 8
12.5

### Ejercicio 11

Modifica el ejemplo para solicitar números hasta que se introduzca uno válido y distinto de cero.

In [32]:
# Escribe aquí tu solución
numero_valido = False

while numero_valido == False:
    try:
        numero = int(input("Introduce un número: "))
        resultado = 100 / numero
        print(resultado)
        numero_valido = True
    except ValueError:
        print("Debes introducir un número entero.")
    except ZeroDivisionError:
        print("No se puede dividir entre cero.")

Introduce un número: 9
11.11111111111111

# 11. Módulos y librerías

Podemos importar funcionalidades ya existentes mediante `import`.

En BDIA utilizaremos especialmente NumPy, Pandas, Matplotlib y Scikit-learn.

In [33]:
import math

print(math.sqrt(25))
print(math.pi)

5.0
3.141592653589793

En un notebook podemos instalar un paquete con:

```python
%pip install nombre_paquete
```

No debemos instalar paquetes innecesariamente: muchas librerías que utilizaremos ya están disponibles en Google Colab.

In [34]:
import sys
print(sys.version)

3.13.15 (main, Aug  6 2026, 11:06:22) [GCC 13.3.0]

# 12. Archivos, CSV y JSON

Los datos pueden almacenarse en archivos. El contexto `with` permite trabajar con ellos de forma segura.

In [63]:
texto = """nombre,nota
Ana,8
Luis,6
Marta,9
"""

with open("alumnos.csv", "w", encoding="utf-8") as archivo:
    archivo.write(texto)

with open("alumnos.csv", "r", encoding="utf-8") as archivo:
    contenido = archivo.read()

print(contenido)

nombre,nota
Ana,8
Luis,6
Marta,9

## JSON

JSON es un formato habitual para intercambiar datos, especialmente en APIs.

In [70]:
import json

alumno = {
    "nombre": "Ana",
    "nota": 8.5,
    "aprobado": True
}

texto_json = json.dumps(alumno, ensure_ascii=False, indent=2)
print(texto_json)

recuperado = json.loads(texto_json)
print(recuperado["nombre"])

print(texto_json[0])
# print(type(texto_json))
# print(type(recuperado))

{
  "nombre": "Ana",
  "nota": 8.5,
  "aprobado": true
}
Ana
{

# 13. NumPy

NumPy proporciona arrays numéricos eficientes y es una base importante para el trabajo con datos y Machine Learning.

In [71]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])

print(a)
print(b)

[1 2 3]
[[1 2]
 [3 4]]

In [73]:
print("shape:", a.shape)
print("ndim:", a.ndim)
print("size:", a.size)
print("dtype:", a.dtype)

shape: (3,)
ndim: 1
size: 3
dtype: int64

## Crear arrays

In [81]:
print(np.zeros(5))
print(np.ones(4))
print(np.arange(0, 50, 2))
print(np.linspace(0, 50, 26))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1.]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34.
 36. 38. 40. 42. 44. 46. 48. 50.]

## Indexación y slicing

In [82]:
a = np.array([10, 20, 30, 40, 50])
print(a[0])
print(a[-1])
print(a[1:4])

10
50
[20 30 40]

In [103]:
# matriz = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
# print(matriz[0, 1])
# print(matriz[:, 1])
# print(matriz[1, :])

# print(np.mean(matriz))
# print(np.mean(matriz, axis=1))
# print(np.mean(matriz, axis=0))

# print(np.max(matriz, axis=1))

otra = np.array([[1, 9, 2],
                 [3, 4, 8],
                 [7, 5, 6]])

print(np.max(otra, axis=0))
print(np.max(otra, axis=1))

[7 9 8]
[9 8 7]

## Vectorización y agregaciones

Podemos operar con un array completo sin escribir un bucle explícito.

In [104]:
precios = np.array([10, 20, 30, 40])
print(precios * 1.21)

[12.1 24.2 36.3 48.4]

In [105]:
datos = np.array([10, 20, 30, 40, 50])
print("media:", np.mean(datos))
print("mínimo:", np.min(datos))
print("máximo:", np.max(datos))
print("suma:", np.sum(datos))

media: 30.0
mínimo: 10
máximo: 50
suma: 150

## Máscaras booleanas

In [106]:
temperaturas = np.array([18, 21, 25, 19, 30, 17])
print(temperaturas > 20)
print(temperaturas[temperaturas > 20])

[False  True  True False  True False]
[21 25 30]

### Ejercicio 12

Crea un array con diez temperaturas y calcula la media, mínimo, máximo y las temperaturas superiores a la media.

In [122]:
# Escribe aquí tu solución
temperaturas2 = np.array([-5, 10, 48, 26, 21, 32, 0, 19, 29, 26])
media2 = np.mean(temperaturas2)
print(f"media: {round(media2, 2)}")
print("mínima:", np.min(temperaturas2))
print("máxima:", np.max(temperaturas2))
print(temperaturas2[temperaturas2 > media2])

media: 20.6
mínima: -5
máxima: 48
[48 26 21 32 29 26]

# 14. Pandas

Pandas está orientado a la manipulación y análisis de datos tabulares.

Su estructura principal es el `DataFrame`.

In [124]:
import pandas as pd

datos = {
    "nombre": ["Ana", "Luis", "Marta", "Carlos"],
    "edad": [20, 21, 19, 22],
    "nota": [8.5, 6.0, 9.0, 7.0]
}

df = pd.DataFrame(datos)
df

   nombre  edad  nota
0     Ana    20   8.5
1    Luis    21   6.0
2   Marta    19   9.0
3  Carlos    22   7.0

## Inspección de un DataFrame

In [134]:
print(df.head())
print("\nShape:", df.shape)
print("\nDescribe:")
print(df.describe(include="all"))
print("\nInfo:")
df.info()

   nombre  edad  nota
0     Ana    20   8.5
1    Luis    21   6.0
2   Marta    19   9.0
3  Carlos    22   7.0

Shape: (4, 3)

Describe:
       nombre       edad      nota
count       4   4.000000  4.000000
unique      4        NaN       NaN
top       Ana        NaN       NaN
freq        1        NaN       NaN
mean      NaN  20.500000  7.625000
std       NaN   1.290994  1.376893
min       NaN  19.000000  6.000000
25%       NaN  19.750000  6.750000
50%       NaN  20.500000  7.750000
75%       NaN  21.250000  8.625000
max       NaN  22.000000  9.000000

Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   nombre  4 non-null      object
 1   edad    4 non-null      int64
 2   nota    4 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 228.0+ bytes

## Seleccionar columnas

In [136]:
print(df["nota"])
print(df[["nombre", "nota"]])
print(df["nombre"])

0    8.5
1    6.0
2    9.0
3    7.0
Name: nota, dtype: float64
   nombre  nota
0     Ana   8.5
1    Luis   6.0
2   Marta   9.0
3  Carlos   7.0
0       Ana
1      Luis
2     Marta
3    Carlos
Name: nombre, dtype: object

## `loc` e `iloc`

In [163]:
print(df.loc[0])
print(df.iloc[0])
print(df.iloc[2:4, 2])
print(df.iloc[2:4, 2:3])

# df_alumnos = df.set_index("nombre")
# print(df_alumnos)

# print(df_alumnos.loc["Ana"])   # busca la fila que SE LLAMA Ana
# print(df_alumnos.iloc[0])      # busca la fila que está en la POSICIÓN 0

nombre    Ana
edad       20
nota      8.5
Name: 0, dtype: object
nombre    Ana
edad       20
nota      8.5
Name: 0, dtype: object
2    9.0
3    7.0
Name: nota, dtype: float64
   nota
2   9.0
3   7.0

## Filtrar datos

In [164]:
aprobados = df[df["nota"] >= 5]
aprobados

   nombre  edad  nota
0     Ana    20   8.5
1    Luis    21   6.0
2   Marta    19   9.0
3  Carlos    22   7.0

In [166]:
seleccion = df[(df["edad"] >= 20) & (df["nota"] >= 7)]
seleccion

   nombre  edad  nota
0     Ana    20   8.5
3  Carlos    22   7.0

## Crear columnas

In [167]:
df["aprobado"] = df["nota"] >= 5
df["nota_doble"] = df["nota"] * 2
df

   nombre  edad  nota  aprobado  nota_doble
0     Ana    20   8.5      True        17.0
1    Luis    21   6.0      True        12.0
2   Marta    19   9.0      True        18.0
3  Carlos    22   7.0      True        14.0

## Valores nulos

In [168]:
df2 = pd.DataFrame({
    "nombre": ["Ana", "Luis", "Marta", "Carlos"],
    "nota": [8.5, None, 9.0, 7.0]
})

print(df2.isna())
print(df2.isna().sum())

   nombre   nota
0   False  False
1   False   True
2   False  False
3   False  False
nombre    0
nota      1
dtype: int64

In [169]:
df2["nota_rellena"] = df2["nota"].fillna(df2["nota"].mean())
df2

   nombre  nota  nota_rellena
0     Ana   8.5      8.500000
1    Luis   NaN      8.166667
2   Marta   9.0      9.000000
3  Carlos   7.0      7.000000

## Leer CSV

Una operación que utilizaremos constantemente será:

```python
pd.read_csv("datos.csv")
```

In [170]:
from io import StringIO

csv = """producto,categoria,precio,cantidad
Teclado,Periféricos,30,4
Ratón,Periféricos,15,10
Monitor,Pantallas,180,2
Webcam,Periféricos,50,3
"""

ventas = pd.read_csv(StringIO(csv))
ventas

  producto    categoria  precio  cantidad
0  Teclado  Periféricos      30         4
1    Ratón  Periféricos      15        10
2  Monitor    Pantallas     180         2
3   Webcam  Periféricos      50         3

### Ejercicio 13

Trabaja con el DataFrame anterior:

1. crea `importe = precio * cantidad`;
2. filtra las ventas superiores a 100 €;
3. calcula el importe total por categoría.

In [196]:
# Escribe aquí tu solución
ventas["importe"] = ventas["precio"]*ventas["cantidad"]
display(ventas)

venta_superior100 = ventas[ventas["importe"] > 100]
display(venta_superior100)

importe_por_categoria = ventas.groupby("categoria")["importe"].sum()
display(importe_por_categoria)

  producto    categoria  precio  cantidad  importe
0  Teclado  Periféricos      30         4      120
1    Ratón  Periféricos      15        10      150
2  Monitor    Pantallas     180         2      360
3   Webcam  Periféricos      50         3      150

  producto    categoria  precio  cantidad  importe
0  Teclado  Periféricos      30         4      120
1    Ratón  Periféricos      15        10      150
2  Monitor    Pantallas     180         2      360
3   Webcam  Periféricos      50         3      150

categoria
Pantallas      360
Periféricos    420
Name: importe, dtype: int64

# 15. Limpieza y transformación

En datos reales encontraremos valores ausentes, tipos incorrectos y columnas que necesitan transformación.

Operaciones habituales de Pandas son:

- `isna()` / `isnull()`
- `dropna()`
- `fillna()`
- `sort_values()`
- creación de columnas
- filtros
- conversiones de tipo

In [197]:
datos = pd.DataFrame({
    "producto": ["A", "B", "C", "D"],
    "precio": [10, None, 30, 20],
    "cantidad": [2, 4, None, 3]
})

datos

  producto  precio  cantidad
0        A    10.0       2.0
1        B     NaN       4.0
2        C    30.0       NaN
3        D    20.0       3.0

In [191]:
datos["precio"] = datos["precio"].fillna(datos["precio"].mean())
datos["cantidad"] = datos["cantidad"].fillna(0)
datos["importe"] = datos["precio"] * datos["cantidad"]
datos.sort_values("importe", ascending=False)

  producto  precio  cantidad  importe
1        B    20.0       4.0     80.0
3        D    20.0       3.0     60.0
0        A    10.0       2.0     20.0
2        C    30.0       0.0      0.0

# 16. Agrupaciones y combinación de datos

`groupby()` permite calcular estadísticas por categorías.

In [198]:
ventas = pd.DataFrame({
    "producto": ["A", "A", "B", "B", "A"],
    "categoria": ["X", "X", "Y", "Y", "X"],
    "cantidad": [10, 5, 7, 8, 3]
})

ventas.groupby("producto")["cantidad"].sum()

producto
A    18
B    15
Name: cantidad, dtype: int64

## `merge()`

Sirve para combinar tablas relacionadas mediante una clave.

In [199]:
clientes = pd.DataFrame({
    "cliente_id": [1, 2, 3],
    "nombre": ["Ana", "Luis", "Marta"]
})

pedidos = pd.DataFrame({
    "cliente_id": [1, 1, 2, 3],
    "importe": [100, 50, 75, 120]
})

clientes.merge(pedidos, on="cliente_id")

   cliente_id nombre  importe
0           1    Ana      100
1           1    Ana       50
2           2   Luis       75
3           3  Marta      120

### Ejercicio 14

Crea dos DataFrames:

- `clientes`: identificador, nombre y ciudad;
- `pedidos`: identificador de pedido, identificador de cliente e importe.

Únelos mediante `merge()` y calcula el importe total por ciudad.

In [209]:
# Escribe aquí tu solución

# Declaramos el primer DataFrame, el de clientes
clientes = pd.DataFrame({
    "identificador de cliente": [1, 2, 3, 4, 5], # Esta columna, será el nexo de ambas tablas
    "nombre": ["Andrés", "Marta", "María", "Jennifer", "Rodrígo"],
    "ciudad": ["Almunia de San Juan", "Almunia de San Juan", "Monzón", "Zaragoza", "Monzón"]
})
# Declaramos el segundo DataFrame, el de pedidos
pedidos = pd.DataFrame({
    "identificador de pedido": [1, 2, 3, 4, 5, 6 ,7, 8, 9, 10],
    "identificador de cliente": [1, 5, 5, 2, 3, 1, 4, 1, 2, 2], # Aquí la ponemos igual
    "precio": [10.99, 50, 28.40, 12, 99.99, 256.96, 547, 28.32, 51, 4]
})
# Con merge, unimos ambas tablas en una, gracias al nexo de unión
pedidos_cliente = clientes.merge(pedidos, on="identificador de cliente")
# Con groupby le decimos que coja la columna ciudad y que sume la columna de precio, y nos muestre por ciudad, el importe total de los pedidos
importe_total_ciudad = pedidos_cliente.groupby("ciudad")["precio"].sum()
importe_total_ciudad

ciudad
Almunia de San Juan    363.27
Monzón                 178.39
Zaragoza               547.00
Name: precio, dtype: float64

# 17. APIs REST

Una API REST permite que una aplicación obtenga datos de otro servicio mediante HTTP.

Una petición `GET` puede devolver JSON. Ese JSON puede convertirse después en estructuras Python o en un DataFrame.

Vamos a practicar con una API pública de prueba.

In [218]:
import requests

url = "https://jsonplaceholder.typicode.com/users"
respuesta = requests.get(url, timeout=10)

print("Código HTTP:", respuesta.status_code)
datos = respuesta.json()
datos [:2]

Código HTTP: 200

[{'id': 1,
  'name': 'Leanne Graham',
  'username': 'Bret',
  'email': 'Sincere@april.biz',
  'address': {'street': 'Kulas Light',
   'suite': 'Apt. 556',
   'city': 'Gwenborough',
   'zipcode': '92998-3874',
   'geo': {'lat': '-37.3159', 'lng': '81.1496'}},
  'phone': '1-770-736-8031 x56442',
  'website': 'hildegard.org',
  'company': {'name': 'Romaguera-Crona',
   'catchPhrase': 'Multi-layered client-server neural-net',
   'bs': 'harness real-time e-markets'}},
 {'id': 2,
  'name': 'Ervin Howell',
  'username': 'Antonette',
  'email': 'Shanna@melissa.tv',
  'address': {'street': 'Victor Plains',
   'suite': 'Suite 879',
   'city': 'Wisokyburgh',
   'zipcode': '90566-7771',
   'geo': {'lat': '-43.9509', 'lng': '-34.4618'}},
  'phone': '010-692-6593 x09125',
  'website': 'anastasia.net',
  'company': {'name': 'Deckow-Crist',
   'catchPhrase': 'Proactive didactic contingency',
   'bs': 'synergize scalable supply-chains'}}]

In [214]:
usuarios = pd.DataFrame(datos)
usuarios[["name", "email"]].head()

               name                      email
0     Leanne Graham          Sincere@april.biz
1      Ervin Howell          Shanna@melissa.tv
2  Clementine Bauch         Nathan@yesenia.net
3  Patricia Lebsack  Julianne.OConner@kory.org
4  Chelsey Dietrich   Lucio_Hettinger@annie.ca

### Ejercicio 15

Utiliza el DataFrame de usuarios:

1. cuenta cuántos usuarios hay;
2. muestra sus nombres;
3. muestra los correos;
4. inspecciona las columnas disponibles.

In [225]:
# Escribe aquí tu solución
usuarios = pd.DataFrame(datos)
print(usuarios.shape[0])

10

# 18. Preparación para Machine Learning

Más adelante trabajaremos con Scikit-learn.

Una idea fundamental es separar:

- `X`: variables de entrada;
- `y`: variable objetivo.

Este patrón aparecerá continuamente en los modelos de Machine Learning.

In [ ]:
datos = pd.DataFrame({
    "horas_estudio": [2, 4, 5, 7, 8, 10],
    "asistencia": [60, 70, 75, 85, 90, 95],
    "nota": [4, 5, 6, 7, 8, 9]
})

X = datos[["horas_estudio", "asistencia"]]
y = datos["nota"]

print("X")
print(X)
print("\ny")
print(y)

## Flujo que utilizaremos durante el curso

```text
datos
  ↓
lectura / adquisición
  ↓
inspección
  ↓
limpieza
  ↓
transformación
  ↓
X e y
  ↓
modelo
  ↓
predicción
  ↓
evaluación
```

Por eso los fundamentos de Python, NumPy y Pandas son una parte esencial de la base del módulo.

# 19. Mini proyecto final

Vamos a integrar los conceptos aprendidos en un pequeño análisis de ventas.

## Datos

El conjunto contiene producto, categoría, precio y cantidad.

In [ ]:
ventas = pd.DataFrame({
    "producto": [
        "Portátil", "Ratón", "Teclado", "Monitor",
        "Portátil", "Ratón", "Webcam", "Monitor",
        "Teclado", "Portátil"
    ],
    "categoria": [
        "Informática", "Periféricos", "Periféricos", "Pantallas",
        "Informática", "Periféricos", "Periféricos", "Pantallas",
        "Periféricos", "Informática"
    ],
    "precio": [900, 20, 45, 220, 900, 20, 60, 220, 45, 900],
    "cantidad": [1, 5, 3, 2, 2, 8, 4, 1, 5, 1]
})

ventas

## Parte 1. Inspección

Comprueba las dimensiones, tipos y estadísticas.

In [ ]:
# Escribe aquí tu solución

## Parte 2. Transformación

Crea una columna `importe`.

In [ ]:
# Escribe aquí tu solución

## Parte 3. Análisis

Calcula:

- importe total;
- producto con mayor cantidad vendida;
- importe por categoría;
- ventas superiores a 500 €.

In [ ]:
# Escribe aquí tu solución

## Parte 4. Reto

Añade un descuento, calcula el importe final y determina qué categoría genera más ingresos.

Intenta resolverlo utilizando únicamente los conceptos aprendidos en este cuaderno.

In [ ]:
# Escribe aquí tu solución

# Referencia rápida

## Python

```python
type(x)
len(x)
range(inicio, fin)
enumerate(iterable)
zip(a, b)
sum(valores)
min(valores)
max(valores)
```

## NumPy

```python
np.array()
np.zeros()
np.ones()
np.arange()
np.linspace()
np.mean()
np.sum()
np.min()
np.max()
```

## Pandas

```python
pd.DataFrame()
pd.read_csv()
df.head()
df.tail()
df.info()
df.describe()
df.shape
df["columna"]
df.loc[]
df.iloc[]
df.isna()
df.dropna()
df.fillna()
df.groupby()
df.merge()
df.sort_values()
```